### PR TITLE
Set up CI: travis and codecov and eslint

### PR DESCRIPTION
**Pull request by AsalaKM**
### Relates #42 #38 
1. set up eslint for both of client and server sides 
2. linking our website with travis

### CODE REVIEW

**Comment by RamyAlshurafa** [comment]
Hey @AsalaKM 
`npm test` will not test the client side.
you need to add these into your script to solve the previous issue and test the client side
`cd client && npm install &&  npm test`

**Comment by AsalaKM** [comment]
Really Thanks @RamyAlshurafa 
Is it OK now !?

**Comment by RamyAlshurafa** [comment]
no worries, It's good.
I think we still need to set up `codecov`, and maybe `mongodb`
take a look here please 
https://github.com/techforbetter/myPickle/blob/master/.travis.yml

**Comment by AsalaKM** [comment]
I see @RamyAlshurafa :+1: 
Many Thanks!

**Pull request merged**
